import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/lms/AppShell";
import { Sparkles, Plus, X, Calendar, Clock, Layers } from "lucide-react";
import { useEffect, useState } from "react";
import { api, ScheduleBlock } from "@/lib/api";
import { toast } from "sonner";

export const Route = createFileRoute("/schedule")({
  head: () => ({ meta: [{ title: "Schedule · Neuron LMS" }] }),
  component: Schedule,
});

const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const hours = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];

// Preset options for manual blocks
const toneOptions = [
  { label: "Primary Blue", value: "bg-primary/85 text-primary-foreground border-l-4 border-primary shadow" },
  { label: "Deep Violet", value: "bg-violet/85 text-foreground border-l-4 border-violet shadow" },
  { label: "Coral Red", value: "bg-coral/85 text-foreground border-l-4 border-coral shadow" },
  { label: "Sky Cyan", value: "bg-sky/85 text-foreground border-l-4 border-sky shadow" },
];

function Schedule() {
  const [blocks, setBlocks] = useState<ScheduleBlock[]>([]);
  const [loading, setLoading] = useState(true);

  // Form states
  const [showAddModal, setShowAddModal] = useState(false);
  const [title, setTitle] = useState("");
  const [selectedDay, setSelectedDay] = useState(0);
  const [selectedStart, setSelectedStart] = useState(9);
  const [selectedLen, setSelectedLen] = useState(1);
  const [selectedTone, setSelectedTone] = useState(toneOptions[0].value);
  const [isAiBlock, setIsAiBlock] = useState(false);

  // AI Suggestions list
  const suggestions = [
    { day: 2, start: 15, len: 1, t: "🎯 Math Quiz Prep", tone: "bg-coral/85 text-foreground border-l-4 border-coral shadow", ai: true, label: "Wednesday 15:00 (1h)" },
    { day: 4, start: 14, len: 2, t: "⚡ Deep Focus Block", tone: "bg-violet/85 text-foreground border-l-4 border-violet shadow", ai: true, label: "Friday 14:00 (2h)" },
    { day: 5, start: 11, len: 2, t: "📚 DSA Quiz Study", tone: "bg-sky/85 text-foreground border-l-4 border-sky shadow", ai: true, label: "Saturday 11:00 (2h)" },
  ];

  const fetchBlocks = () => {
    setLoading(true);
    api.getScheduleBlocks()
      .then((data) => {
        setBlocks(data);
        setLoading(false);
      })
      .catch((err) => {
        console.error("Error loading schedule blocks:", err);
        setLoading(false);
      });
  };

  useEffect(() => {
    fetchBlocks();
  }, []);

  const handleAddBlock = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) {
      toast.error("Please provide an event title");
      return;
    }

    try {
      await api.createScheduleBlock(
        selectedDay,
        selectedStart,
        selectedLen,
        title.trim(),
        selectedTone,
        isAiBlock
      );
      toast.success("Schedule block added successfully!");
      setShowAddModal(false);
      setTitle("");
      fetchBlocks();
    } catch (err: any) {
      console.error("Error adding block:", err);
      toast.error("Failed to add block to schedule");
    }
  };

  const handleAcceptSuggestion = async (sug: typeof suggestions[0]) => {
    try {
      await api.createScheduleBlock(
        sug.day,
        sug.start,
        sug.len,
        sug.t,
        sug.tone,
        true
      );
      toast.success(`Accepted suggestion: ${sug.t}!`);
      fetchBlocks();
    } catch (err) {
      console.error("Error accepting suggestion:", err);
      toast.error("Failed to add suggested block");
    }
  };

  return (
    <AppShell>
      <div className="max-w-7xl mx-auto space-y-6 pb-12">
        <div className="text-left">
          <div className="text-xs font-mono uppercase tracking-[0.2em] text-primary">/ smart schedule</div>
          <h1 className="font-display text-3xl sm:text-4xl font-bold tracking-tight mt-2">
            This week, optimized for you.
          </h1>
          <p className="text-muted-foreground mt-1 text-sm">
            Manage your studies manually or accept suggestions generated by Neuron AI based on focus peaks.
          </p>
        </div>

        {/* AI study block banner */}
        <div className="rounded-2xl border border-primary/30 bg-primary/5 p-4 flex items-start gap-3">
          <Sparkles className="h-5 w-5 text-primary shrink-0 mt-0.5" />
          <div className="text-sm text-left">
            <div className="font-medium text-foreground">Interactive Study Planner</div>
            <div className="text-muted-foreground text-xs mt-1">
              Add blocks manually on the calendar below or click [+] in the side panel to add study slots suggested by the tutor.
            </div>
          </div>
        </div>

        {/* Layout: calendar left, suggestions right */}
        <div className="grid lg:grid-cols-4 gap-6">
          <div className="lg:col-span-3">
            {loading ? (
              <div className="grid place-items-center h-[50vh] rounded-2xl border border-border bg-card/40">
                <div className="text-center space-y-2">
                  <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-primary mx-auto" />
                  <p className="text-muted-foreground text-sm font-mono uppercase tracking-wider">Syncing Planner Events...</p>
                </div>
              </div>
            ) : (
              /* week grid */
              <div className="rounded-2xl border border-border bg-card/40 overflow-x-auto">
                <div className="min-w-[760px]">
                  <div className="grid grid-cols-[60px_repeat(7,1fr)] border-b border-border">
                    <div />
                    {days.map((d) => (
                      <div key={d} className="px-3 py-3 text-xs font-mono uppercase tracking-[0.15em] text-muted-foreground border-l border-border">
                        {d}
                      </div>
                    ))}
                  </div>
                  <div className="grid grid-cols-[60px_repeat(7,1fr)] relative">
                    {/* hour labels */}
                    <div>
                      {hours.map((h) => (
                        <div key={h} className="h-14 px-2 py-1 text-[10px] font-mono text-muted-foreground border-b border-border/40 text-left">
                          {h}:00
                        </div>
                      ))}
                    </div>
                    {/* day columns */}
                    {days.map((_, di) => (
                      <div key={di} className="relative border-l border-border">
                        {hours.map((h) => (
                          <div key={h} className="h-14 border-b border-border/40" />
                        ))}
                        {blocks
                          .filter((b) => b.day === di)
                          .map((b, i) => {
                            const top = (b.start - hours[0]) * 56;
                            const height = b.len * 56 - 4;
                            return (
                              <div
                                key={i}
                                className={`absolute left-1 right-1 rounded-lg px-2 py-1.5 text-[11px] leading-tight ${b.tone} shadow-lg text-left overflow-hidden`}
                                style={{ top, height }}
                              >
                                <div className="font-semibold truncate flex items-center gap-0.5">
                                  {b.ai && <Sparkles className="h-3 w-3 text-amber-300 shrink-0" />}
                                  <span>{b.t}</span>
                                </div>
                                <div className="text-[9px] opacity-90 font-mono mt-0.5">
                                  {b.start}:00 – {b.start + b.len}:00
                                </div>
                              </div>
                            );
                          })}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Side panel: manual add + suggestions */}
          <div className="lg:col-span-1 space-y-6">
            {/* Quick Actions */}
            <div className="rounded-2xl border border-border bg-card/60 p-5 space-y-4">
              <h3 className="font-display font-bold text-sm text-foreground tracking-wider uppercase text-left">Quick Actions</h3>
              <button
                onClick={() => setShowAddModal(true)}
                className="w-full flex items-center justify-center gap-2 rounded-xl bg-primary text-primary-foreground py-2.5 text-xs font-semibold shadow hover:scale-[1.01] transition"
              >
                <Plus className="h-4 w-4" />
                <span>Add Study Block</span>
              </button>
            </div>

            {/* Suggestions list */}
            <div className="rounded-2xl border border-border bg-card/60 p-5 space-y-4 text-left">
              <h3 className="font-display font-bold text-sm text-foreground tracking-wider uppercase flex items-center gap-1.5">
                <Sparkles className="h-4 w-4 text-primary" /> AI Suggested Blocks
              </h3>
              <p className="text-[11px] text-muted-foreground leading-normal">
                Suggested slots based on times when you scored highest on quizzes:
              </p>

              <div className="space-y-3 pt-1">
                {suggestions.map((sug, i) => (
                  <div key={i} className="p-3 bg-background/50 border border-border rounded-xl space-y-2 text-xs flex justify-between items-start gap-2">
                    <div className="space-y-1">
                      <div className="font-semibold text-foreground">{sug.t}</div>
                      <div className="text-[10px] text-muted-foreground font-mono">{sug.label}</div>
                    </div>
                    <button
                      onClick={() => handleAcceptSuggestion(sug)}
                      className="rounded-lg bg-primary/20 text-primary border border-primary/30 p-1 text-[10px] font-bold hover:bg-primary/30 transition shrink-0"
                      title="Add to schedule"
                    >
                      <Plus className="h-3 w-3" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Add Block Manual Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 backdrop-blur-sm px-4">
          <div className="w-full max-w-md rounded-3xl border border-border bg-card/90 p-6 shadow-2xl relative animate-in fade-in zoom-in-95 duration-200 text-left">
            <button
              onClick={() => setShowAddModal(false)}
              className="absolute top-5 right-5 p-1.5 hover:bg-accent rounded-lg text-muted-foreground hover:text-foreground transition-colors"
            >
              <X className="h-5 w-5" />
            </button>

            <h2 className="font-display text-lg font-bold mb-4 flex items-center gap-2">
              <Calendar className="h-5 w-5 text-primary" /> Add Custom Study Block
            </h2>

            <form onSubmit={handleAddBlock} className="space-y-4 text-sm">
              <div>
                <label className="block text-xs font-mono uppercase tracking-wider text-muted-foreground mb-1">Block Title</label>
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="w-full bg-background border border-border rounded-xl px-4 py-2 outline-none focus:border-primary transition"
                  placeholder="e.g. Chemistry Homework Review"
                  required
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-mono uppercase tracking-wider text-muted-foreground mb-1">Day of week</label>
                  <select
                    value={selectedDay}
                    onChange={(e) => setSelectedDay(Number(e.target.value))}
                    className="w-full bg-background border border-border rounded-xl px-3 py-2 outline-none focus:border-primary transition"
                  >
                    {days.map((d, i) => (
                      <option key={i} value={i}>{d}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-mono uppercase tracking-wider text-muted-foreground mb-1">Start Time</label>
                  <select
                    value={selectedStart}
                    onChange={(e) => setSelectedStart(Number(e.target.value))}
                    className="w-full bg-background border border-border rounded-xl px-3 py-2 outline-none focus:border-primary transition"
                  >
                    {hours.map((h) => (
                      <option key={h} value={h}>{h}:00</option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-mono uppercase tracking-wider text-muted-foreground mb-1">Duration (Hours)</label>
                  <select
                    value={selectedLen}
                    onChange={(e) => setSelectedLen(Number(e.target.value))}
                    className="w-full bg-background border border-border rounded-xl px-3 py-2 outline-none focus:border-primary transition"
                  >
                    <option value={1}>1 Hour</option>
                    <option value={2}>2 Hours</option>
                    <option value={3}>3 Hours</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-mono uppercase tracking-wider text-muted-foreground mb-1">Color Style</label>
                  <select
                    value={selectedTone}
                    onChange={(e) => setSelectedTone(e.target.value)}
                    className="w-full bg-background border border-border rounded-xl px-3 py-2 outline-none focus:border-primary transition"
                  >
                    {toneOptions.map((opt, i) => (
                      <option key={i} value={opt.value}>{opt.label}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="flex items-center gap-2 py-2">
                <input
                  type="checkbox"
                  id="aiCheck"
                  checked={isAiBlock}
                  onChange={(e) => setIsAiBlock(e.target.checked)}
                  className="rounded border-border text-primary focus:ring-primary h-4 w-4 bg-background"
                />
                <label htmlFor="aiCheck" className="text-xs text-muted-foreground select-none cursor-pointer flex items-center gap-1">
                  Mark as AI-optimized placement block <Sparkles className="h-3 w-3 text-primary" />
                </label>
              </div>

              <button
                type="submit"
                className="w-full rounded-xl bg-primary text-primary-foreground font-semibold py-3 shadow-[var(--glow-lime)] hover:scale-[1.01] transition"
              >
                Create Study Block
              </button>
            </form>
          </div>
        </div>
      )}
    </AppShell>
  );
}

export default Schedule;
